package mcpserver

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/soggycactus/paprika-3-mcp/internal/paprika"
)

type NewServerOptions struct {
	Version  string
	Username string
	Password string
	Paprika  *paprika.Client
	Logger   *slog.Logger
}

func NewServer(opts NewServerOptions) (*Server, error) {
	paprika3, err := paprika.NewClient(opts.Username, opts.Password, opts.Version, opts.Logger)
	if err != nil {
		return nil, err
	}

	s := server.NewMCPServer("paprika-3-mcp", opts.Version, server.WithResourceCapabilities(false, false))
	return &Server{
		paprika3: paprika3,
		server:   s,
		logger:   opts.Logger,
	}, nil
}

type Server struct {
	paprika3 *paprika.Client
	logger   *slog.Logger
	server   *server.MCPServer
}

func (s *Server) Start() {
	go s.updateResources()

	createRecipeTool := mcp.NewTool("create_paprika_recipe",
		mcp.WithDescription("Save new recipes generated by LLMs in the Paprika 3 app"),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.DefaultString("")),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.DefaultString("")),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.DefaultString("")),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.DefaultString("")),
	)
	updateRecipeTool := mcp.NewTool("update_paprika_recipe",
		mcp.WithDescription("Update existing recipes in the Paprika 3 app"),
		mcp.WithString("uid", mcp.Description("The UID of the recipe"), mcp.Required()),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.Required()),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.Required()),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.Required()),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.Required()),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.Required()),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.Required()),
	)
	searchRecipesTool := mcp.NewTool("search_recipes",
		mcp.WithDescription("Search and list recipes from your Paprika 3 collection"),
		mcp.WithString("query", mcp.Description("Search term to find recipes (searches name, ingredients, and description). Leave empty to list all recipes."), mcp.DefaultString("")),
		mcp.WithNumber("limit", mcp.Description("Maximum number of recipes to return"), mcp.DefaultNumber(10)),
	)
	exploreAPITool := mcp.NewTool("explore_paprika_api",
		mcp.WithDescription("Explore Paprika API endpoints to find meal planning and grocery features"),
	)
	inspectMealTool := mcp.NewTool("inspect_meal_data",
		mcp.WithDescription("Inspect the raw structure of existing meals to understand the API format"),
	)
	listMealPlanTool := mcp.NewTool("list_meal_plan",
		mcp.WithDescription("List your meal plan from Paprika showing scheduled meals by date"),
		mcp.WithString("start_date", mcp.Description("Start date in YYYY-MM-DD format (optional)"), mcp.DefaultString("")),
		mcp.WithString("end_date", mcp.Description("End date in YYYY-MM-DD format (optional)"), mcp.DefaultString("")),
	)
	listGroceriesTool := mcp.NewTool("list_groceries",
		mcp.WithDescription("List your current grocery/shopping list from Paprika"),
		mcp.WithString("filter", mcp.Description("Filter by: 'purchased', 'unpurchased', or 'all'"), mcp.DefaultString("all")),
	)
	addMealTool := mcp.NewTool("add_meal_to_plan",
		mcp.WithDescription("Add a meal to your Paprika meal plan calendar"),
		mcp.WithString("date", mcp.Description("Date in YYYY-MM-DD format"), mcp.Required()),
		mcp.WithString("meal_name", mcp.Description("Name of the meal"), mcp.Required()),
		mcp.WithNumber("meal_type", mcp.Description("Meal type: 0=Breakfast, 1=Lunch, 2=Dinner"), mcp.DefaultNumber(2)),
		mcp.WithString("recipe_uid", mcp.Description("UID of the recipe (optional - use search_recipes to find UIDs)"), mcp.DefaultString("")),
	)
	removeMealTool := mcp.NewTool("remove_meal_from_plan",
		mcp.WithDescription("Remove a meal from your Paprika meal plan calendar"),
		mcp.WithString("meal_uid", mcp.Description("UID of the meal to remove (get from list_meal_plan)"), mcp.Required()),
	)
	s.server.AddTools(server.ServerTool{
		Tool:    createRecipeTool,
		Handler: s.createRecipe,
	}, server.ServerTool{
		Tool:    updateRecipeTool,
		Handler: s.updateRecipe,
	}, server.ServerTool{
		Tool:    searchRecipesTool,
		Handler: s.searchRecipes,
	}, server.ServerTool{
		Tool:    exploreAPITool,
		Handler: s.exploreAPI,
	}, server.ServerTool{
		Tool:    listMealPlanTool,
		Handler: s.listMealPlan,
	}, server.ServerTool{
		Tool:    listGroceriesTool,
		Handler: s.listGroceries,
	}, server.ServerTool{
		Tool:    addMealTool,
		Handler: s.addMealToPlan,
	}, server.ServerTool{
		Tool:    removeMealTool,
		Handler: s.removeMealFromPlan,
	}, server.ServerTool{
		Tool:    inspectMealTool,
		Handler: s.inspectMealData,
	})

	if err := server.ServeStdio(s.server); err != nil {
		s.logger.Error("Server error", "err", err)
	}
}

func (s *Server) updateResources() {
	s.addResources()

	ticker := time.NewTicker(1 * time.Minute)
	for range ticker.C {
		s.addResources()
	}
}

func (s *Server) addResources() {
	s.logger.Info("Updating recipe resources")
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	// List all recipes to expose them as resources
	recipes, err := s.paprika3.ListRecipes(ctx)
	if err != nil {
		s.logger.Error("failed to list paprika recipes", "err", err)
		return
	}

	if len(recipes.Result) >= 10 {
		s.logger.Info("adding recipes resources concurrently")
		s.addResourcesConcurrently(recipes)
		return
	}

	for _, r := range recipes.Result {
		if err := s.addRecipeResource(r.UID); err != nil {
			s.logger.Error("failed to add recipe as MCP resource", "err", err)
		}
	}
}

func (s *Server) addRecipeResource(uid string) error {
	start := time.Now()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.GetRecipe(ctx, uid)
	if err != nil {
		return err
	}

	if recipe.InTrash {
		return nil
	}

	resourceContents := mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}

	s.server.AddResource(mcp.NewResource(fmt.Sprintf("paprika://recipes/%s", recipe.UID), recipe.Name, mcp.WithResourceDescription(recipe.ResourceDescription()), mcp.WithMIMEType("text/markdown")), func(ctx context.Context, request mcp.ReadResourceRequest) ([]mcp.ResourceContents, error) {
		return []mcp.ResourceContents{resourceContents}, nil
	})

	duration := time.Since(start)
	s.logger.Info("Added resource", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return nil
}

func (s *Server) addResourcesConcurrently(recipes *paprika.RecipeList) {
	buffer := make(chan struct{}, 10)

	for _, r := range recipes.Result {
		go func() (err error) {
			buffer <- struct{}{}
			defer func() {
				<-buffer
			}()

			defer func(err error) {
				if err != nil {
					s.logger.Error("failed to add recipe as MCP resource", "err", err)
				}
			}(err)

			return s.addRecipeResource(r.UID)
		}()
	}
}

func (s *Server) createRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	// Handle optional string fields safely
	servings := ""
	if val, ok := req.Params.Arguments["servings"].(string); ok {
		servings = val
	}
	prepTime := ""
	if val, ok := req.Params.Arguments["prep_time"].(string); ok {
		prepTime = val
	}
	cookTime := ""
	if val, ok := req.Params.Arguments["cook_time"].(string); ok {
		cookTime = val
	}
	description := ""
	if val, ok := req.Params.Arguments["description"].(string); ok {
		description = val
	}
	notes := ""
	if val, ok := req.Params.Arguments["notes"].(string); ok {
		notes = val
	}
	difficulty := ""
	if val, ok := req.Params.Arguments["difficulty"].(string); ok {
		difficulty = val
	}

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
	})
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Created recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func (s *Server) updateRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	uid, ok := req.Params.Arguments["uid"].(string)
	if !ok || len(uid) == 0 {
		return nil, errors.New("uid is required")
	}
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	// Handle optional string fields safely
	description := ""
	if val, ok := req.Params.Arguments["description"].(string); ok {
		description = val
	}
	servings := ""
	if val, ok := req.Params.Arguments["servings"].(string); ok {
		servings = val
	}
	prepTime := ""
	if val, ok := req.Params.Arguments["prep_time"].(string); ok {
		prepTime = val
	}
	cookTime := ""
	if val, ok := req.Params.Arguments["cook_time"].(string); ok {
		cookTime = val
	}
	notes := ""
	if val, ok := req.Params.Arguments["notes"].(string); ok {
		notes = val
	}
	difficulty := ""
	if val, ok := req.Params.Arguments["difficulty"].(string); ok {
		difficulty = val
	}

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		UID:         uid,
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
	})
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Updated recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func (s *Server) searchRecipes(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	
	// Get search query and limit
	query := ""
	if val, ok := req.Params.Arguments["query"].(string); ok {
		query = strings.ToLower(strings.TrimSpace(val))
	}
	
	limit := 10
	if val, ok := req.Params.Arguments["limit"].(float64); ok {
		limit = int(val)
	}
	
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	
	// Get all recipes
	recipeList, err := s.paprika3.ListRecipes(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list recipes: %w", err)
	}
	
	// Fetch full recipe details and filter
	var matchedRecipes []paprika.Recipe
	for _, recipeInfo := range recipeList.Result {
		if len(matchedRecipes) >= limit {
			break
		}
		
		recipe, err := s.paprika3.GetRecipe(ctx, recipeInfo.UID)
		if err != nil {
			s.logger.Error("failed to get recipe details", "uid", recipeInfo.UID, "error", err)
			continue
		}
		
		if recipe.InTrash {
			continue
		}
		
		// If no query, include all recipes
		if query == "" {
			matchedRecipes = append(matchedRecipes, *recipe)
			continue
		}
		
		// Search in recipe name, ingredients, and description
		searchText := strings.ToLower(recipe.Name + " " + recipe.Ingredients + " " + recipe.Description)
		if strings.Contains(searchText, query) {
			matchedRecipes = append(matchedRecipes, *recipe)
		}
	}
	
	duration := time.Since(start)
	s.logger.Info("Search completed", "query", query, "matches", len(matchedRecipes), "duration", duration)
	
	// Format results
	var resultText strings.Builder
	if query != "" {
		resultText.WriteString(fmt.Sprintf("# Search Results for \"%s\"\n\n", query))
	} else {
		resultText.WriteString("# All Recipes\n\n")
	}
	
	if len(matchedRecipes) == 0 {
		if query != "" {
			resultText.WriteString("No recipes found matching your search.\n")
		} else {
			resultText.WriteString("No recipes found in your collection.\n")
		}
	} else {
		resultText.WriteString(fmt.Sprintf("Found %d recipe(s):\n\n", len(matchedRecipes)))
		
		for i, recipe := range matchedRecipes {
			resultText.WriteString(fmt.Sprintf("%d. **%s**\n", i+1, recipe.Name))
			if recipe.Description != "" {
				resultText.WriteString(fmt.Sprintf("   _%s_\n", recipe.Description))
			}
			resultText.WriteString(fmt.Sprintf("   UID: %s\n", recipe.UID))
			if recipe.Servings != "" {
				resultText.WriteString(fmt.Sprintf("   Servings: %s\n", recipe.Servings))
			}
			if recipe.PrepTime != "" || recipe.CookTime != "" {
				timeInfo := ""
				if recipe.PrepTime != "" {
					timeInfo += fmt.Sprintf("Prep: %s", recipe.PrepTime)
				}
				if recipe.CookTime != "" {
					if timeInfo != "" {
						timeInfo += ", "
					}
					timeInfo += fmt.Sprintf("Cook: %s", recipe.CookTime)
				}
				resultText.WriteString(fmt.Sprintf("   Time: %s\n", timeInfo))
			}
			resultText.WriteString("\n")
		}
	}
	
	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) addMealToPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	
	// Get parameters
	date, ok := req.Params.Arguments["date"].(string)
	if !ok || date == "" {
		return nil, errors.New("date is required")
	}
	mealName, ok := req.Params.Arguments["meal_name"].(string)
	if !ok || mealName == "" {
		return nil, errors.New("meal_name is required")
	}
	
	mealType := 2 // Default to dinner
	if val, ok := req.Params.Arguments["meal_type"].(float64); ok {
		mealType = int(val)
	}
	
	recipeUID := ""
	if val, ok := req.Params.Arguments["recipe_uid"].(string); ok {
		recipeUID = strings.TrimSpace(val)
	}
	
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	
	// Create meal plan entry with ALL required fields
	// Format date correctly: "YYYY-MM-DD 00:00:00"
	formattedDate := date + " 00:00:00"
	
	meal := paprika.MealPlan{
		Date:      formattedDate,
		Name:      mealName,
		Type:      mealType,
		RecipeUID: recipeUID,
		OrderFlag: 0,
	}
	
	// Save the meal plan entry
	savedMeal, err := s.paprika3.SaveMealPlan(ctx, meal)
	if err != nil {
		return nil, fmt.Errorf("failed to add meal to plan: %w", err)
	}
	
	duration := time.Since(start)
	s.logger.Info("Added meal to plan", "date", date, "meal", mealName, "type", mealType, "duration", duration)
	
	// Format result
	var resultText strings.Builder
	resultText.WriteString("# Meal Added Successfully\n\n")
	
	mealTypeStr := "Dinner"
	switch mealType {
	case 0:
		mealTypeStr = "Breakfast"
	case 1:
		mealTypeStr = "Lunch"
	case 2:
		mealTypeStr = "Dinner"
	}
	
	resultText.WriteString(fmt.Sprintf("Added **%s** as %s on %s\n\n", mealName, mealTypeStr, date))
	resultText.WriteString(fmt.Sprintf("- **Date**: %s\n", date))
	resultText.WriteString(fmt.Sprintf("- **Meal**: %s\n", mealName))
	resultText.WriteString(fmt.Sprintf("- **Type**: %s\n", mealTypeStr))
	if recipeUID != "" {
		resultText.WriteString(fmt.Sprintf("- **Recipe ID**: %s\n", recipeUID))
	}
	resultText.WriteString(fmt.Sprintf("- **Meal ID**: %s\n\n", savedMeal.UID))
	
	resultText.WriteString("The meal has been added to your Paprika meal plan calendar.\n")
	
	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) removeMealFromPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	
	// Get meal UID parameter
	mealUID, ok := req.Params.Arguments["meal_uid"].(string)
	if !ok || mealUID == "" {
		return nil, errors.New("meal_uid is required")
	}
	
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	
	// Delete the meal plan entry
	err := s.paprika3.DeleteMealPlan(ctx, mealUID)
	if err != nil {
		return nil, fmt.Errorf("failed to remove meal from plan: %w", err)
	}
	
	duration := time.Since(start)
	s.logger.Info("Removed meal from plan", "meal_uid", mealUID, "duration", duration)
	
	// Format result
	var resultText strings.Builder
	resultText.WriteString("# Meal Removed Successfully\n\n")
	resultText.WriteString(fmt.Sprintf("Removed meal with ID **%s** from your meal plan.\n\n", mealUID))
	resultText.WriteString("The meal has been deleted from your Paprika meal plan calendar.\n")
	
	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) inspectMealData(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	
	// Get meal plan data
	mealPlanResp, err := s.paprika3.ListMealPlan(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get meal plan: %w", err)
	}
	
	duration := time.Since(start)
	s.logger.Info("Retrieved meal plan for inspection", "count", len(mealPlanResp.Result), "duration", duration)
	
	// Format results with detailed inspection
	var resultText strings.Builder
	resultText.WriteString("# Meal Plan Data Inspection\n\n")
	
	if len(mealPlanResp.Result) == 0 {
		resultText.WriteString("No meals found in your meal plan.\n")
	} else {
		resultText.WriteString(fmt.Sprintf("Found %d meal entries. Showing detailed structure:\n\n", len(mealPlanResp.Result)))
		
		// Show first few meals with full JSON structure
		limit := 5
		if len(mealPlanResp.Result) < limit {
			limit = len(mealPlanResp.Result)
		}
		
		for i, meal := range mealPlanResp.Result[:limit] {
			resultText.WriteString(fmt.Sprintf("## Meal %d: %s\n", i+1, meal.Name))
			resultText.WriteString(fmt.Sprintf("- **Date**: %s\n", meal.Date))
			resultText.WriteString(fmt.Sprintf("- **UID**: %s\n", meal.UID))
			resultText.WriteString(fmt.Sprintf("- **Recipe UID**: %s\n", meal.RecipeUID))
			resultText.WriteString(fmt.Sprintf("- **Type**: %d\n", meal.Type))
			resultText.WriteString(fmt.Sprintf("- **Order Flag**: %d\n", meal.OrderFlag))
			resultText.WriteString(fmt.Sprintf("- **Deleted**: %t\n", meal.Deleted))
			
			// JSON representation
			mealJSON, err := json.MarshalIndent(meal, "", "  ")
			if err == nil {
				resultText.WriteString("\n**Raw JSON Structure:**\n```json\n")
				resultText.WriteString(string(mealJSON))
				resultText.WriteString("\n```\n\n")
			}
		}
		
		if len(mealPlanResp.Result) > limit {
			resultText.WriteString(fmt.Sprintf("... and %d more meals\n", len(mealPlanResp.Result)-limit))
		}
	}
	
	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) listMealPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	
	// Get date filters if provided
	startDate := ""
	if val, ok := req.Params.Arguments["start_date"].(string); ok {
		startDate = strings.TrimSpace(val)
	}
	endDate := ""
	if val, ok := req.Params.Arguments["end_date"].(string); ok {
		endDate = strings.TrimSpace(val)
	}
	
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	
	// Get meal plan from Paprika
	mealPlanResp, err := s.paprika3.ListMealPlan(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get meal plan: %w", err)
	}
	
	// Filter by date range if specified
	var filteredMeals []paprika.MealPlan
	for _, meal := range mealPlanResp.Result {
		if startDate != "" && meal.Date < startDate {
			continue
		}
		if endDate != "" && meal.Date > endDate {
			continue
		}
		filteredMeals = append(filteredMeals, meal)
	}
	
	duration := time.Since(start)
	s.logger.Info("Retrieved meal plan", "total", len(mealPlanResp.Result), "filtered", len(filteredMeals), "duration", duration)
	
	// Format results
	var resultText strings.Builder
	resultText.WriteString("# Meal Plan\n\n")
	
	if startDate != "" || endDate != "" {
		resultText.WriteString(fmt.Sprintf("Showing meals from %s to %s\n\n", startDate, endDate))
	}
	
	if len(filteredMeals) == 0 {
		resultText.WriteString("No meals found in the specified date range.\n")
	} else {
		resultText.WriteString(fmt.Sprintf("Found %d scheduled meal(s):\n\n", len(filteredMeals)))
		
		// Group by date
		mealsByDate := make(map[string][]paprika.MealPlan)
		for _, meal := range filteredMeals {
			mealsByDate[meal.Date] = append(mealsByDate[meal.Date], meal)
		}
		
		// Sort dates
		dates := make([]string, 0, len(mealsByDate))
		for date := range mealsByDate {
			dates = append(dates, date)
		}
		// Simple sort for dates in YYYY-MM-DD format
		for i := 0; i < len(dates); i++ {
			for j := i + 1; j < len(dates); j++ {
				if dates[i] > dates[j] {
					dates[i], dates[j] = dates[j], dates[i]
				}
			}
		}
		
		for _, date := range dates {
			meals := mealsByDate[date]
			resultText.WriteString(fmt.Sprintf("## %s\n", date))
			
			for _, meal := range meals {
				mealType := "Meal"
				switch meal.Type {
				case 1:
					mealType = "Lunch"
				case 2:
					mealType = "Dinner"
				case 0:
					mealType = "Breakfast"
				}
				
				resultText.WriteString(fmt.Sprintf("- **%s**: %s", mealType, meal.Name))
				if meal.RecipeUID != "" {
					resultText.WriteString(fmt.Sprintf(" (Recipe ID: %s)", meal.RecipeUID))
				}
				resultText.WriteString("\n")
			}
			resultText.WriteString("\n")
		}
	}
	
	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) listGroceries(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	
	// Get filter parameter
	filter := "all"
	if val, ok := req.Params.Arguments["filter"].(string); ok {
		filter = strings.ToLower(strings.TrimSpace(val))
	}
	
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	
	// Get groceries from Paprika
	groceryResp, err := s.paprika3.ListGroceries(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get groceries: %w", err)
	}
	
	// Filter items based on purchase status
	var filteredItems []paprika.GroceryItem
	for _, item := range groceryResp.Result {
		switch filter {
		case "purchased":
			if item.Purchased {
				filteredItems = append(filteredItems, item)
			}
		case "unpurchased":
			if !item.Purchased {
				filteredItems = append(filteredItems, item)
			}
		default: // "all"
			filteredItems = append(filteredItems, item)
		}
	}
	
	duration := time.Since(start)
	s.logger.Info("Retrieved groceries", "total", len(groceryResp.Result), "filtered", len(filteredItems), "filter", filter, "duration", duration)
	
	// Format results
	var resultText strings.Builder
	resultText.WriteString("# Grocery List\n\n")
	
	if len(filteredItems) == 0 {
		resultText.WriteString("No grocery items found.\n")
	} else {
		resultText.WriteString(fmt.Sprintf("Found %d grocery item(s):\n\n", len(filteredItems)))
		
		// Group by aisle
		itemsByAisle := make(map[string][]paprika.GroceryItem)
		for _, item := range filteredItems {
			aisle := item.Aisle
			if aisle == "" {
				aisle = "Other"
			}
			itemsByAisle[aisle] = append(itemsByAisle[aisle], item)
		}
		
		// Sort aisles alphabetically
		aisles := make([]string, 0, len(itemsByAisle))
		for aisle := range itemsByAisle {
			aisles = append(aisles, aisle)
		}
		for i := 0; i < len(aisles); i++ {
			for j := i + 1; j < len(aisles); j++ {
				if aisles[i] > aisles[j] {
					aisles[i], aisles[j] = aisles[j], aisles[i]
				}
			}
		}
		
		for _, aisle := range aisles {
			items := itemsByAisle[aisle]
			resultText.WriteString(fmt.Sprintf("## %s\n", aisle))
			
			for _, item := range items {
				status := "☐"
				if item.Purchased {
					status = "☑"
				}
				
				resultText.WriteString(fmt.Sprintf("%s **%s**", status, item.Ingredient))
				if item.Quantity != "" {
					resultText.WriteString(fmt.Sprintf(" (%s)", item.Quantity))
				}
				if item.Recipe != "" {
					resultText.WriteString(fmt.Sprintf(" - for %s", item.Recipe))
				}
				if item.Instruction != "" {
					resultText.WriteString(fmt.Sprintf(" _%s_", item.Instruction))
				}
				resultText.WriteString("\n")
			}
			resultText.WriteString("\n")
		}
	}
	
	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) exploreAPI(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	
	// First try to get meal plan data
	mealPlanResp, err := s.paprika3.ListMealPlan(ctx)
	if err != nil {
		s.logger.Error("failed to get meal plan data", "error", err)
	}
	
	// Try to get grocery data
	groceryResp, err := s.paprika3.ListGroceries(ctx)
	if err != nil {
		s.logger.Error("failed to get grocery data", "error", err)
	}
	
	// Explore other API endpoints
	err = s.paprika3.ExploreAPI(ctx)
	if err != nil {
		s.logger.Error("failed to explore API", "error", err)
	}
	
	duration := time.Since(start)
	s.logger.Info("API exploration completed", "duration", duration)
	
	var resultText strings.Builder
	resultText.WriteString("# Paprika API Exploration Results\n\n")
	resultText.WriteString("Explored various API endpoints to find meal planning and grocery features.\n\n")
	
	if mealPlanResp != nil {
		resultText.WriteString(fmt.Sprintf("## Meal Plan API\nFound %d meal entries\n\n", len(mealPlanResp.Result)))
	}
	
	if groceryResp != nil {
		resultText.WriteString(fmt.Sprintf("## Grocery API\nFound %d grocery items\n\n", len(groceryResp.Result)))
	}
	
	resultText.WriteString("Check the server logs for detailed exploration results of all attempted endpoints.\n")
	
	return mcp.NewToolResultText(resultText.String()), nil
}
